import { ShareLanguage, ShareSocial, Lang } from './types'

export function getLang(): Lang {
  const lang = navigator.language
  return lang ? (lang.substr(0, 2).toLowerCase() as Lang) : 'en'
}

export const shareOption: ShareSocial = {
  sms: 'SMS',
  messenger: 'Messenger',
  whatsapp: 'WhatsApp',
  twitter: 'Twitter',
  linkedin: 'Linkedin',
  telegram: 'Telegram',
  facebook: 'Facebook',
  skype: 'Skype',
}

export const shareLang: ShareLanguage = {
  cs: {
    shareTitle: 'Sdílet',
    cancel: 'Zrušit',
    copy: 'Kopírovat',
    print: 'Tisk',
    email: 'E-mail',
    selectSms: 'Vyberte kontakt',
  },
  sk: {
    shareTitle: 'Zdieľať',
    cancel: 'Zrušiť',
    copy: 'Kopírovat',
    print: 'Tlač',
    email: 'E-mail',
    selectSms: 'Vyberte kontakt',
  },
  ja: {
    shareTitle: '共有する',
    cancel: 'キャンセル',
    copy: 'コピーする',
    print: '印刷する',
    email: 'E-mail',
    selectSms: '連絡先を選択してください',
  },
  zh: {
    shareTitle: '分享',
    cancel: '取消',
    copy: '複製連結',
    print: '列印',
    email: 'E-mail',
    selectSms: '選擇聯絡人',
  },
  pt: {
    shareTitle: 'Compartilhar',
    cancel: 'Cancelar',
    copy: 'Copiar',
    print: 'Imprimir',
    email: 'E-mail',
    selectSms: 'Selecione um contato',
  },
  en: {
    shareTitle: 'Share',
    cancel: 'Cancel',
    copy: 'Copy',
    print: 'Print',
    email: 'E-mail',
    selectSms: 'Pick a contact',
  },
  es: {
    shareTitle: 'Compartir',
    cancel: 'Cancelar',
    copy: 'Copiar',
    print: 'Imprimir',
    email: 'Correo',
    selectSms: 'Seleccionar un contacto',
  },
  fr: {
    shareTitle: 'Partager',
    cancel: 'Annuler',
    copy: 'Copier',
    print: 'Imprimer',
    email: 'E-mail',
    selectSms: 'Veuillez choisir un contact',
  },
  de: {
    shareTitle: 'Teilen',
    cancel: 'Abbrechen',
    copy: 'Kopieren',
    print: 'Drucken',
    email: 'E-mail',
    selectSms: 'Wählen Sie einen Kontakt aus',
  },
  nl: {
    shareTitle: 'Delen',
    cancel: 'Annuleren',
    copy: 'Kopiëren',
    print: 'Printen',
    email: 'E-mail',
    selectSms: 'Selecteer een contact',
  },
  sv: {
    shareTitle: 'Dela',
    cancel: 'Avbryt',
    copy: 'Kopiera',
    print: 'Skriv ut',
    email: 'E-mail',
    selectSms: 'Välj en kontakt',
  },
  da: {
    shareTitle: 'Del',
    cancel: 'Luk',
    copy: 'Kopiér',
    print: 'Udskriv',
    email: 'E-mail',
    selectSms: 'Vælg en kontaktperson',
  },
  // Deprecated, use `da` instead.
  dk: {
    shareTitle: 'Del',
    cancel: 'Luk',
    copy: 'Kopiér',
    print: 'Udskriv',
    email: 'E-mail',
    selectSms: 'Vælg en kontaktperson',
  },
  ru: {
    shareTitle: 'Поделиться',
    cancel: 'Отмена',
    copy: 'Скопировать',
    print: 'Печать',
    email: 'Э-майл',
    selectSms: 'Выбери контакт',
  },
  tr: {
    shareTitle: 'Paylaş',
    cancel: 'Vazgeç',
    copy: 'Kopyala',
    print: 'Yazdır',
    email: 'E-posta',
    selectSms: 'Bir kişi seç',
  },
  ko: {
    shareTitle: '공유',
    cancel: '취소',
    copy: '링크 복사',
    print: '인쇄',
    email: 'E-mail',
    selectSms: '연락처를 선택하세요',
  },
  ta: {
    shareTitle: 'பகிர்',
    cancel: 'இரத்து',
    copy: 'நகலெடு',
    print: 'அச்சிடு',
    email: 'மின்னஞ்சல்',
    selectSms: 'ஒரு தொடர்பைத் தேர்வுசெய்க',
  },
  pl: {
    shareTitle: 'Dzielić',
    cancel: 'Anuluj',
    copy: 'Kopiuj',
    print: 'Wydrukować',
    email: 'E-mail',
    selectSms: 'Wybierz kontakt',
  },
}
