export enum SpeekAction {
  CreateOrJoin = 'create-or-join',
  KnockKnock = 'knock-knock',
  Available = 'available',
  Created = 'created',
  Exited = 'exited',
  Ready = 'ready',
  Joined = 'joined',
  Full = 'full',
  Candidate = 'candidate',
  Connection = 'connection',
  Offer = 'offer',
  Answer = 'answer',
  Screen = 'screen',
}
